<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net40</TargetFramework>
    <AssemblyName>Guides</AssemblyName>
    <RootNamespace>YxGuides</RootNamespace>
    <LangVersion>7.3</LangVersion>
    <DebugType>none</DebugType>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <NoWarn>CS1701;CS1702</NoWarn>
    <OutputPath>plugins\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <YxRefs Condition="'$(YxRefs)' == ''">$(MSBuildThisFileDirectory)refs\</YxRefs>
    <YxSdkDir Condition="'$(YxSdkDir)' == ''">$(MSBuildThisFileDirectory)sdk-bin\</YxSdkDir>
    <YxSdkDir Condition="!Exists('$(YxSdkDir)Yx.ModSdk.Core.dll') And Exists('$(YxSdkDir)net40\Yx.ModSdk.Core.dll')">$(YxSdkDir)net40\</YxSdkDir>
    <WebRequestRef>$(YxRefs)UnityEngine.UnityWebRequestModule.dll</WebRequestRef>
    <WebRequestRef Condition="!Exists('$(WebRequestRef)')">$(YxRefs)dummy\UnityEngine.UnityWebRequestModule.dll</WebRequestRef>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="src\*.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net40" Version="1.0.3" PrivateAssets="all" />
    <ProjectReference Condition="Exists('..\..\sdk\Yx.ModSdk.Core\Yx.ModSdk.Core.csproj')" Include="..\..\sdk\Yx.ModSdk.Core\Yx.ModSdk.Core.csproj"><Private>false</Private></ProjectReference>
    <ProjectReference Condition="Exists('..\..\sdk\Yx.ModSdk\Yx.ModSdk.csproj')" Include="..\..\sdk\Yx.ModSdk\Yx.ModSdk.csproj"><Private>false</Private></ProjectReference>
    <Reference Condition="!Exists('..\..\sdk\Yx.ModSdk.Core\Yx.ModSdk.Core.csproj')" Include="Yx.ModSdk.Core"><HintPath>$(YxSdkDir)Yx.ModSdk.Core.dll</HintPath><Private>false</Private></Reference>
    <Reference Condition="!Exists('..\..\sdk\Yx.ModSdk\Yx.ModSdk.csproj')" Include="Yx.ModSdk"><HintPath>$(YxSdkDir)Yx.ModSdk.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="UnityEngine.UnityWebRequestModule"><HintPath>$(WebRequestRef)</HintPath><Private>false</Private></Reference>
    <Reference Include="DarkSun.HotUpdate"><HintPath>$(YxRefs)DarkSun.HotUpdate.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="DarkSun.UI"><HintPath>$(YxRefs)DarkSun.UI.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="DarkSun.Utility"><HintPath>$(YxRefs)DarkSun.Utility.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="wProtobuf"><HintPath>$(YxRefs)wProtobuf.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UniRx"><HintPath>$(YxRefs)UniRx.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UniTask"><HintPath>$(YxRefs)UniTask.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.TextMeshPro"><HintPath>$(YxRefs)Unity.TextMeshPro.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(YxRefs)UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UI"><HintPath>$(YxRefs)UnityEngine.UI.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UIModule"><HintPath>$(YxRefs)UnityEngine.UIModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.InputLegacyModule"><HintPath>$(YxRefs)UnityEngine.InputLegacyModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.TextRenderingModule"><HintPath>$(YxRefs)UnityEngine.TextRenderingModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.TextCoreModule"><HintPath>$(YxRefs)UnityEngine.TextCoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="ILRuntime"><HintPath>$(YxRefs)ILRuntime.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="ILRuntime.Mono.Cecil"><HintPath>$(YxRefs)ILRuntime.Mono.Cecil.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
